title: Ong Hock Soon
logo: /assets/img//head-logo.png
description: Driven mid-career individual focused on evolving through continuous learning and self-development.
# show_downloads: false
theme: jekyll-theme-minimal
